### ISSUE TITLE
Layout configuration (through configuration file) doesn't work 

### ISSUE THREAD

**Issue by petitout** [m-reiniger/log4js-syslog-appender#1]
Hi,
first thanks for your contirubution, it is very nice.
I have a log4js.json configuration file in which I try to define the following appender : 

> {
>       "type": "log4js-syslog-appender",
>       "facility": "local0",
>       "hostname": "localhost",
>       "port": 514,
>       "layout": {
>         "type": "pattern",
>         "pattern": "%d{ABSOLUTE} %[%-5p%] %c %m"
>      }
>  }

During its launch, my application crashes :

> Error: Problem reading log4js config { appenders: 
> ....
> Error was "log4js configuration problem for { type: 'log4js-syslog-appender', 
> .....

The bug resides in the following line of your "configure" function :

> layout = layouts.layout(config.layout.type, config.layout);

which should be replaced by :

> layout = **log4js.**layouts.layout(config.layout.type, config.layout);

Thanks

**Comment by m-reiniger** [comment]
Very appreciated. 

Your Pull Request is merged. I will create a new npm package in a minute.
