### ISSUE TITLE
Discussion about "duplicate" fields in log messages

### ISSUE THREAD

**Issue by matttrawicki** [m-reiniger/log4js-syslog-appender#4]
Good day! On both my Mac and Yocto Linux, log messages have a timestamp and computer name prepended by the syslog process, as well as the long format timestamp and computer name added by ain2. The duplication is a bit noisy and I'm seeking to reduce it.

Current
Apr  7 10:53:21 matthews-imac 2016-04-07T15: 53:21.130Z matthews-imac.--.--.---.com MyAppname[12345]: And finally, the actual log message!

Preferred
Apr  7 10:53:21 matthews-imac MyAppname[12345]: And finally, the actual log message!

This is one option I've come up with: https://github.com/matttrawicki/log4js-syslog-appender/commit/c9d392f0658e3fcfab2d49194a47e4a9204e683a, though I'm not sure it fits the log4js mindset. Seeking your advice. Thanks and best regards, Matthew

**Comment by matttrawicki** [comment]
@m-reiniger Please respond

**Comment by m-reiniger** [comment]
If I am not mistaken, this is what layouts are used for. Please take a look at log4js Layouts first.

And sorry, for the late reply. The notification from github must have collided with my spam filter.

**Comment by matttrawicki** [comment]
No worries, thanks for responding! Yes, I would agree that a custom layout should allow control over the formatting. The challenge in this case is that the text from the default formatter or even a custom log4js formatter is given to ain, but then ain further formats the message, adding the computer name, process id and timestamp. Ain does offer the option to pass its constructor a "message composer" function. But because ain is your dependency, there isn't a way for a consumer to configure its [message composer](https://github.com/phuesler/ain/blob/master/index.js#L268). That's what support I added in [this branch](https://github.com/matttrawicki/log4js-syslog-appender/tree/abbreviatedFormat). But, that doesn't feel very log4js-ish. It's also very technical, exposing the concepts of the facility and severity.

**Comment by m-reiniger** [comment]
I'll take a closer look at it when I find the time. Maybe we find a nice way to do this. But I have to read back into ain, since I haven't really used it for quite a while. 

Nevertheless, thanks for the feedback.

**Comment by m-reiniger** [comment]
I'll take a close look at it when I find the time. Maybe there is a nice way to do this. But I have to read back into ain and log4js, since I haven't used them in quite a while. 

The problem I see, since this is just an appender, it would have to be configured in the log4js configuration. But as of now, I am not really sure if this is the way to go. I don't really want to pollute the log4js config with an ain message composer config. 

Nevertheless, thanks for the feedback.

**Comment by m-reiniger** [comment]
As you might have seen, I didn't have the time to implement your requested changes. And I will not have the time to do so in the future. Please forgive me and thank you for using this package. It's outdated.
