### ISSUE TITLE
Node v6 support

### ISSUE THREAD

**Issue by kuritkaj** [m-reiniger/log4js-syslog-appender#5]
Hello,

current version installation is failing. The ain2 dependency should be updated to version 2.0.0 in order to resolve it.

Regards,
Me

**Comment by matttrawicki** [comment]
👍 I'm trying to move up to Node 6 as well. Happy to submit a PR if you'd like.

**Comment by m-reiniger** [comment]
Hi, 

thanks for reminding me. ;) 

Dependencies are updated and a new version (0.3.0) is released.

**Comment by m-reiniger** [comment]
PS: I also updated log4js, which changes the default message format a little bit.
