### ISSUE TITLE
Use a format more normal for Syslog

### ISSUE THREAD

**Issue by singpolyma** [m-reiniger/log4js-syslog-appender#6]
Normally syslog is more like:

```
tag: message
```

Currently, using this package, I get this in `/var/log/syslog`

```
:07.222Z _notifications[19597]:Loaded config:  { listen_port: 4000,#012  redis_url: 'REDACTED' }
```

Where my tag is set to `node_notifications` ... so something is getting eaten here, probably because of the strange format used.

I am using default rsyslog config on Ubuntu 14.04.

**Comment by m-reiniger** [comment]
If this is still needed, feel free to make a pull request. The code is just a couple lines. I will not do any coding for this anymore. But thanks for using it.
